#!/bin/bash
# {{ ansible_managed }}

#Author: Toby

#VARIABLES NAGIOS
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

PROGNAME=`basename $0 .sh`
VERSION="v0.1"

print_help() {
    echo $PROGNAME $VERSION
    echo ""
    echo "$PROGNAME is a Nagios plugin to check Linux firewall status"
    echo ""
    echo "Usage:"
    echo "     $PROGNAME -l # Show current Linux firewall status"
    echo "     $PROGNAME -h # Print this help message"
    exit $OK
}

while getopts ":lh" opt
do
  case ${opt} in
    h|\?) print_help ;;
       l) continue ;;
  esac
done

if [ $OPTIND -eq 1 ]
then
  print_help
fi

if [ -f /etc/os-release ]
then
  source /etc/os-release
  VID=$(echo $VERSION_ID | awk -F. '{print $1}')
elif [ -f /etc/redhat-release ]
then
  VID=$(awk -F'[.| ]' '{print tolower($1)$3}' /etc/redhat-release)
fi

# systemd
systemdstatus()
{
case $1 in
  'active') echo -e "OK: $fw is $status" ; exit $OK ;;
  'inactive') echo -e "CRITICAL: $fw is $status" ; exit $CRITICAL ;;
  '*') echo -e "UNKNOWN: unknown $fw status" ; exit $UNKNOWN ;;
esac
}

# init
initdstatus()
{
case $1 in
  'iptables: Firewall is not running.') echo -e "CRITICAL: $fw is not running" ; exit $CRITICAL ;;
  *) echo -e "OK: $fw is active" ; exit $OK ;;
esac
}

case ${ID}${VID} in
  centos7|centos8) fw=firewalld ; status=$(systemctl is-active $fw) ; systemdstatus $status ;;
  centos5|centos6) fw=iptables ; status=$(service $fw status) ; initdstatus $status ;;
  ubuntu20|ubuntu18|ubuntu16) fw=ufw ; status=$(systemctl is-active $fw) ; systemdstatus $status ;;
  *) echo -e "WARNING: $PROGNAME doesn't currently support this OS" ; exit $WARNING ;;
esac

